from _tests.unittests.test_enigma import Test_Enigma
from _tests.unittests.test_entry_wheel import Test_EntryWheel
from _tests.unittests.test_misc import Test_Misc
from _tests.unittests.test_reflector import Test_Reflector
from _tests.unittests.test_scrambler import Test_Scrambler
from _tests.unittests.test_settings import Test_Settings
from _tests.unittests.test_swapper import Test_Swapper
from _tests.unittests.test_switchboard import Test_Switchboard
from _tests.unittests.test_rotor import Test_Rotor
